imports:
    - { resource: legacy_aliases.yml }

parameters:
#    parameter_name: value

services:
    _defaults:
        autowire: true
        autoconfigure: true

    AppBundle\Service\MarkdownTransformer:
        arguments: ['@markdown.parser', '@doctrine_cache.providers.my_markdown_cache']

    AppBundle\Twig\MarkdownExtension: ~

    AppBundle\Security\LoginFormAuthenticator: ~

    AppBundle\Doctrine\HashPasswordListener:
        tags:
            - { name: doctrine.event_subscriber }

    AppBundle\Form\TypeExtension\HelpFormExtension:
        tags:
            - { name: form.type_extension, extended_type: 'Symfony\Component\Form\Extension\Core\Type\FormType'}